---
kind: pipeline
type: docker
name: default
trigger:
  event:
  - push

steps:
- name: Install node modules
  image: node:12-alpine
  commands:
  - npm i

- name: Build
  image: node:12-alpine
  commands:
  - npx ng build --prod
---
kind: signature
hmac: 94539839f8658cee5773a82c6f59f1f5e5c0f4e8c0099fb90eb6e6ebb9413e11

...
