---
kind: pipeline
type: docker
name: default

steps:
- name: Install node modules
  image: node:12-alpine
  commands:
  - npm i

- name: Build
  image: node:12-alpine
  commands:
  - npx ng build --prod

- name: Publish
  image: plugins/gh-pages
  when:
    branch:
    - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: www

---
kind: signature
hmac: 85f501a4ee1ff652f8aeef99bc89ca35d0536f67b4b01ffef9f94ff18a3dec14

...
