---
kind: pipeline
type: docker
name: default

steps:
- name: Install node modules
  image: node:12-alpine
  commands:
  - npm i

- name: Build
  image: node:12-alpine
  commands:
  - npx ng build --prod --deploy-url=https://zyra.github.io/ionic-super-tabs-example/

- name: Publish
  image: plugins/gh-pages
  when:
    branch:
    - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: www

---
kind: signature
hmac: f4d8bef8a5b739fef2e060cce7eb26013cfc0c731aa83485d30f3252048b0718

...
